apiVersion: v1
kind: Secret
metadata:
  name: traefik-forward-auth-secrets
  namespace: kube-system
  labels:
    app: traefik-forward-auth
type: Opaque
data:
  traefik-forward-auth-client-id: ${CLIENT_ID}
  traefik-forward-auth-client-secret: ${CLIENT_SECRET}
  traefik-forward-auth-secret: ${SECRET}
