- name: Install build deps and dotfiles
  hosts: k3s_cluster
  gather_facts: yes
  tags: [server, setup]
  roles:
    - base/build-deps
    - base/dotfiles

- name: Setup k3s
  hosts: k3s_cluster
  gather_facts: yes
  become: yes
  tags: [server, k3s]
  roles:
    - base/k3s/prereq
    - base/k3s/download

- name: k3s Master Node
  hosts: sheol
  become: yes
  roles:
    - base/k3s/master

# - name: k3s Agent Node
#   hosts: agent
#   become: yes
#   roles:
#     - base/k3s/node

- name: Infrastructure
  hosts: sheol
  become: yes
  roles:
    - infra/traefik
    - infra/keycloak
    - infra/traefik-forward-auth
    - infra/grafana
