- name: Install build deps and dotfiles
  hosts: k3s_cluster
  tags: [server, setup]
  roles:
    - build-deps
    - dotfiles

- name: Setup k3d
  hosts: master
  gather_facts: yes
  become: yes
  tags: [server, k3d]
  roles:
    - k3d/download

# - name: Setup k3s
#   hosts: k3s_cluster
#   gather_facts: yes
#   become: yes
#   tags: [server, k3s]
#   roles:
#     - k3s/prereq
#     - k3s/download

# - name: Master Node
#   hosts: master
#   become: yes
#   roles:
#     - k3s/master
#     -

# - name: Agent Node
#   hosts: agent
#   become: yes
#   roles:
#     - k3s/node
