---
- name: load variables
  tags: [common, secrets]
  include_vars: '{{ playbook_dir }}/secrets.env.yaml'

- name: create monitoring namespace
  shell:
    cmd: kubectl create namespace monitoring
  delegate_to: 127.0.0.1
  register: kubectl_grafana_namespace

- name: apply Prometheus cluster role
  shell:
    cmd: kubectl apply -f files/prometheus-cluster-role.yaml
    chdir: '{{ playbook_dir }}/roles/infra/monitoring/prometheus'
  delegate_to: 127.0.0.1
  register: kubectl_prometheus_cluster_role

- name: apply Prometheus config
  shell:
    cmd: kubectl apply -f files/prometheus-config.yaml
    chdir: '{{ playbook_dir }}/roles/infra/monitoring/prometheus'
  delegate_to: 127.0.0.1
  register: kubectl_prometheus_config

- name: apply Prometheus deployment
  shell:
    cmd: kubectl apply -f files/prometheus.yaml
    chdir: '{{ playbook_dir }}/roles/infra/monitoring/prometheus'
  delegate_to: 127.0.0.1
  register: kubectl_prometheus

- name: apply Prometheus ingress
  shell:
    cmd: kubectl apply -f files/prometheus-ingress.yaml
    chdir: '{{ playbook_dir }}/roles/infra/monitoring/prometheus'
  delegate_to: 127.0.0.1
  register: kubectl_prometheus_ingress
