apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-secrets
  namespace: nextcloud
  labels:
    app: nextcloud
type: Opaque
data:
  PG_DB: ${PG_DB}
  PG_USER: ${PG_USER}
  PG_PASS: ${PG_PASS}
  ADMIN_USER: ${ADMIN_USER}
  ADMIN_PASS: ${ADMIN_PASS}
  DOMAIN: ${DOMAIN}
  SMTP_NAME: ${SMTP_NAME}
  SMTP_PASSWORD: ${SMTP_PASSWORD}
  MAIL_FROM_ADDRESS: ${MAIL_FROM_ADDRESS}
