apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-secrets
  namespace: nextcloud
  labels:
    app: nextcloud
type: Opaque
data:
  PG_DB: bmV4dGNsb3Vk
  PG_USER: cm9vdA==
  PG_PASS: Rkpna0J3WkdnOFZmWVVacWJEZVI0
  ADMIN_USER: YWRtaW4=
  ADMIN_PASS: c0xhQkZYR2dUWTM3N2NnUlF5QVVLNGM=
