apiVersion: v1
kind: Service
metadata:
  name: nextcloud
  namespace: nextcloud
  labels:
    app: nextcloud
    component: app
spec:
  selector:
    component: app
  ports:
    - port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
  namespace: nextcloud
  labels:
    app: nextcloud
    component: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
      component: app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nextcloud
        component: app
    spec:
      containers:
        - name: nextcloud
          image: nextcloud:apache
          imagePullPolicy: Always
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  key: MYSQL_DATABASE
                  name: nextcloud-maria-db-secret
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MYSQL_PASSWORD
                  name: nextcloud-maria-db-secret
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  key: MYSQL_USER
                  name: nextcloud-maria-db-secret
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nextcloud-storage
              mountPath: /var/www/html
      restartPolicy: Always
      volumes:
        - name: nextcloud-storage
          persistentVolumeClaim:
            claimName: nextcloud-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-pvc
  namespace: nextcloud
  labels:
    app: nextcloud
    type: local
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20T
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-pv
  labels:
    app: nextcloud
    type: local
spec:
  capacity:
    storage: 20T
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: nextcloud-pvc
    namespace: nextcloud
  local:
    path: /mnt/moriyya
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - sheol
