---

- name: check it k3d cluster exists
  shell:
    cmd: k3d cluster list
  register: k3d_cluster

- name: Print k3d cluster list
  debug:
    var: k3d_cluster.stdout

- name: create k3d cluster
  shell:
    cmd: k3d cluster create Inferno -s 1 -a 1
  when: k3d_cluster.stdout.find('Inferno') == -1

- name: update kubectl config
  shell:
    cmd: k3d kubeconfig merge Inferno --kubeconfig-merge-default
  when: k3d_cluster.stdout.find('Inferno') == -1

# k3d kubeconfig merge Inferno --kubeconfig-merge-default
# k3d kubeconfig merge Inferno -o ~/.kube/config
