---
- name: load variables
  tags: [common, secrets]
  include_vars: '{{ playbook_dir }}/secrets.env.yaml'

- name: apply Alert Manager config
  shell:
    cmd: cat files/alert-manager-config.yaml | envsubst | kubectl apply -f -
    chdir: '{{ playbook_dir }}/roles/infra/monitoring/alert-manager'
  environment:
    DOMAIN: '{{ domain_name }}'
    HOST: '{{ email.smtp.host }}'
    USER: '{{ email.smtp.username }}'
    PASS: '{{ email.smtp.password }}'
  delegate_to: 127.0.0.1
  register: kubectl_prometheus_cluster_role

- name: apply Alert Manager template
  shell:
    cmd: kubectl apply -f files/alert-manager-template.yaml
    chdir: '{{ playbook_dir }}/roles/infra/monitoring/alert-manager'
  delegate_to: 127.0.0.1
  register: kubectl_prometheus_config

- name: apply Alert Manager deployment
  shell:
    cmd: kubectl apply -f files/alert-manager.yaml
    chdir: '{{ playbook_dir }}/roles/infra/monitoring/alert-manager'
  delegate_to: 127.0.0.1
  register: kubectl_prometheus

- name: apply Prometheus ingress
  shell:
    cmd: kubectl apply -f files/alert-manager-ingress.yaml
    chdir: '{{ playbook_dir }}/roles/infra/monitoring/alert-manager'
  delegate_to: 127.0.0.1
  register: kubectl_prometheus_ingress
