apiVersion: v1
kind: Namespace
metadata:
  name: shared
  labels:
    cert-manager-tls: shared # Define namespace label for kubed
---
apiVersion: v1
data:
  ca.crt: ''
  tls.crt: ''
  tls.key: ''
kind: Secret
metadata:
  name: wildcard-powell-place-secret
  namespace: cert-manager
  annotations:
    kubed.appscode.com/sync: "cert-manager-tls= wildcard-powell-place" # Sync certificate to matching namespaces
type: kubernetes.io/tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-powell-place
  namespace: cert-manager
spec:
  secretName: wildcard-powell-place-secret
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer
  commonName: powell.place
  dnsNames:
    - powell.place
    - "*.powell.place"
  privateKey:
    rotationPolicy: Always
