apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    additionalArguments:
      - "--entryPoints.web.proxyProtocol.insecure"
      - "--entryPoints.web.forwardedHeaders.insecure"
      - "--providers.kubernetescrd.allowCrossNamespace=true"
      - "--log.level=INFO"
    dashboard:
      enabled: true
    ports:
      websecure:
        tls:
          enabled: true
      web:
        redirectTo: websecure
    logs:
      access:
        enabled: true
