apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secrets
  namespace: keycloak
  labels:
    app: keycloak
type: Opaque
data:
  PG_DB: ${PG_DB}
  PG_USER: ${PG_USER}
  PG_PASS: ${PG_PASS}
  KC_ADMN: ${KC_ADMN}
  KC_PASS: ${KC_PASS}
  DOMAIN: ${DOMAIN}
