apiVersion: v1
kind: Service
metadata:
  name: keycloak-postgres-db
  namespace: keycloak
  labels:
    app: keycloak
spec:
  selector:
    app: keycloak-postgressql-db
  ports:
    - name: pgql
      port: 5432
      targetPort: 5432
      protocol: TCP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: keycloak-postgressql-db
  namespace: keycloak
  labels:
    app: keycloak
spec:
  serviceName: keycloak-postgressql-db-service
  selector:
    matchLabels:
      app: keycloak-postgressql-db
  replicas: 1
  template:
    metadata:
      labels:
        app: keycloak-postgressql-db
    spec:
      containers:
        - name: keycloak-postgressql-db
          image: postgres:14.5
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
              subPath: pgdata
          env:
            - name: POSTGRES_USER
              value: root #${PG_USER}
            - name: POSTGRES_PASSWORD
              value: LA6nDawJoPhTLDT9GqQu #${PG_PASS}
            - name: POSTGRES_DB
              value: keycloak #${PG_DB}
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata #/data/pgdata
          ports:
            - containerPort: 5432
      terminationGracePeriodSeconds: 60
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes:
          - 'ReadWriteOnce'
        resources:
          requests:
            storage: 10Gi
