apiVersion: v1
kind: Service
metadata:
  name: keycloak-postgres-db
spec:
  selector:
    app: keycloak-postgres-db
  type: LoadBalancer
  ports:
    - name: pgql
      port: 5432
      targetPort: 5432
      protocol: TCP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: keycloak-postgres-db
spec:
  serviceName: keycloak-postgres-db
  replicas: 1
  selector:
    matchLabels:
      app: keycloak-postgres-db
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: keycloak-postgres-db
          image: postgres:latest
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
              subPath: pgdata
          env:
            - name: POSTGRES_USER
              value:
            - name: POSTGRES_PASSWORD
              value:
            - name: POSTGRES_DB
              value: keycloak
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5432
      terminationGracePeriodSeconds: 60
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: 10Gi
