apiVersion: v1
kind: Secret
metadata:
  name: homeassistant-secrets
  namespace: homeassistant
  labels:
    app: homeassistant
type: Opaque
data:
  PG_DB: ${PG_DB}
  PG_USER: ${PG_USER}
  PG_PASS: ${PG_PASS}
