apiVersion: v1
kind: Service
metadata:
  name: homeassistant
  namespace: homeassistant
  labels:
    app: homeassistant
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '8123'
spec:
  selector:
    app: homeassistant
  ports:
    - name: http
      port: 8123
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homeassistant
  namespace: homeassistant
  labels:
    app: homeassistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homeassistant
  template:
    metadata:
      labels:
        app: homeassistant
    spec:
      containers:
        - name: home-assistant
          image: homeassistant/home-assistant:latest
          volumeMounts:
            - mountPath: '/config'
              name: ha-storage
      volumes:
        - name: ha-storage
          persistentVolumeClaim:
            claimName: homeassistant-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homeassistant-pvc
  namespace: homeassistant
  labels:
    app: homeassistant
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
