apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  labels:
    name: grafana-config
  namespace: monitoring
data:
  grafana.ini: |-
    ; [auth]
    ; disable_login_form = false
    ; disable_signout_menu = false
    [auth.generic_oauth]
    enabled = true
    name = Keycloak
    allow_sign_up = true
    api_url = https://keycloak.powell.place/realms/inferno/protocol/openid-connect/userinfo
    auth_url = https://keycloak.powell.place/realms/inferno/protocol/openid-connect/auth
    token_url = https://keycloak.powell.place/realms/inferno/protocol/openid-connect/token
    client_id = grafana
    client_secret = agMym2W8oIct5osulxdl5K20TmktX6U1
    role_attribute_path = contains(groups[*], 'grafana-admin') && 'Admin' || contains(groups[*], 'grafana-dev') && 'Editor' || 'Viewer'
    scopes = profile,email,groups
    [server]
    root_url = https://grafana.powell.place
    ; [users]
    ; allow_org_create = true
    ; allow_sign_up = true
    ; auto_assign_org = true
    ; auto_assign_org_role = Admin
    ; default_theme = dark
    ; login_hint = email or username
    ; verify_email_enabled = false
